# Generated by Django 3.0.5 on 2020-04-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowercasing', models.BooleanField(default=False)),
                ('lemmatization', models.BooleanField(default=False)),
                ('stemming', models.BooleanField(default=False)),
                ('digit_masking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('num_task', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.OneToOneField(db_column='config', on_delete=django.db.models.deletion.CASCADE, to='twecApp.Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='twecApp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='twecApp.Task')),
            ],
        ),
    ]
