# Generated by Django 3.0.4 on 2020-03-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twecApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='document_path',
        ),
    ]
