# Generated by Django 3.0.5 on 2020-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twecApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
