# Generated by Django 3.0.5 on 2020-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twecApp', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name_task',
            field=models.CharField(default='New Task', max_length=200),
        ),
    ]
