# Generated by Django 3.0.5 on 2020-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twecApp', '0003_task_name_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.FilePathField(),
        ),
    ]
