# Generated by Django 3.0.4 on 2020-03-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twecApp', '0003_auto_20200312_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
